### ISSUE TITLE
微信小程序启动问题

### ISSUE THREAD

**Issue by Gotham-Jocker** [zidou-kiyn/ZanaoRobot#2]
微信小程序启动问题，它老是报错缺乏评价组件，请问佬该如何解决哩😭

**Comment by zidou-kiyn** [comment]
[](https://github.com/Ackites/KillWxapkg
)
最近看到的项目，可以去试试看

**Comment by Gotham-Jocker** [comment]
呜呜，感谢大佬，我尝试尝试😘（可怕的评价组件😖）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 晚上7:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zidou-kiyn/ZanaoRobot] 微信小程序启动问题 (Issue #2)




 
https://github.com/Ackites/KillWxapkg
 最近看到的项目，可以去试试看
