### ISSUE TITLE
证书问题还是X-Sc-...问题😭（具体见内容）

### ISSUE THREAD

**Issue by Joker-of-Gotham** [zidou-kiyn/ZanaoRobot#3]
我又来求教大佬啦😭，这半个月一直在断断续续尝试，目前遇到的问题是程序运行后只出警告：
InsecureRequestWarning: Unverified HTTPS request is being made to host 'c.zanao.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
但无论我怎么更新证书都是没作用的

我又回看了你的经验，其中提到了X-Sc-Ah、X-Sc-Nd、X-Sc-Td，但是我现在再在Fiddler上看的时候没看到了，只剩下下面四个：
X-Sc-Version: 2.7.0
X-Requested-With: XMLHttpRequest
X-Sc-Platform: android
X-Sc-Alias: sysu

所以我目前觉得问题可能是下面的一个或几个：
1. 怀疑集市用了自签证书，我去搞到集市的证书，然后导入到程序里就OK了
2. 开发者隐藏了X-Sc-Ah、X-Sc-Nd、X-Sc-Td（这个还算好说，我去解hexview就好了）
3. 开发者改变了X-Sc-Ah、X-Sc-Nd、X-Sc-Td的做法，换了新方法
4. 其他问题

最后附上我的代码：
```
import requests
import urllib3
import logging

http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED')

cookies = {
    'user_token': '...',
    'Hm_lvt_44d055a19f3943caa808501f424e662e': '..., ..., ...',
    'HMACCOUNT': '...',
    'Hm_lpvt_44d055a19f3943caa808501f424e662e': ...',
    'SERVERID': '......|...|...',
}

headers = {
    'Host': 'c.zanao.com',
    'Connection': 'keep-alive',
    'X-Sc-Version': '2.7.0',
    'Accept': 'application/json, text/plain, */*',
    'X-Requested-With': 'XMLHttpRequest',
    'X-Sc-Platform': 'android',
    'X-Sc-Alias': 'sysu',
    'User-Agent': '...',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Dest': 'empty',
    'Referer': 'https://c.zanao.com/l/1T21NcR9',
    # 'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'zh-CN,zh;q=0.9',
}

params = {
    'isIOS': 'false',
}

response = requests.get('https://c.zanao.com/sc-api/mx/tag/hot', params=params, cookies=cookies, headers=headers, verify=False)

with open('0.dat', 'wb') as f:
    f.write(response.content)

```
麻烦佬啦，有幸碰到了为数不多能交流这些技术的朋友，真的觉得好难得(ಥ _ ಥ)

**Comment by zidou-kiyn** [comment]
好像集市升级后不需要那些加密参数了。直接有cookie就能获取了。
代码如下
`import requests

url = "https://c.zanao.com/sc-api/thread/info"
headers = {
    "Host": "c.zanao.com",
    "Connection": "keep-alive",
    "X-Sc-Version": "2.7.0",
    "Accept": "application/json, text/plain, */*",
    "X-Requested-With": "XMLHttpRequest",
    "X-Sc-Platform": "android",
    "X-Sc-Alias": "zzu",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63090b19) XWEB/11177 Flue",
    "Origin": "https://c.zanao.com",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Dest": "empty",
    "Referer": "https://c.zanao.com/l/1Y21NOzl",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "zh-CN,zh;q=0.9",
    "Cookie": "user_token=user_token; SERVERID=SERVERID"
}

# Handling multipart form data
data = {
    "id": (None, "id"),
    "url": (None, "https://c.zanao.com/l/id"),
    "from": (None, ""),
    "isIOS": (None, "false")
}

response = requests.post(url, headers=headers, files=data)

# Print the response content
print(response.text)
`
其中**cookie**里面的**user_token**和**serverid**换成你自己抓出来的
**data中的id和url中的id**也换成你们那边帖子的

**Comment by Gotham-Jocker** [comment]
&nbsp; &nbsp; &nbsp; &nbsp;对的，是这样的，我今天上午弄了一上午弄好了；在开始爬info时会出现ID非法的情况，但后面重写了完整的params后就OK啦😚。
&nbsp; &nbsp; &nbsp; &nbsp;不过在下午的时候又发现了一件尴尬的事，我提取信息的目的用于信息收集整理，所以会用到评价的部分，但评价的url每个id和sign啥的都不一样（还没很仔细看），所以我现在在着手解决自动提取评价部分的问题，并进一步将评价和内容对应，才能再接入AI的api进行后续处理，佬如果有兴趣可以看看怎么把评价部分也实现自动化😉同时收集评价部分可能也可以给gpt提供模板，提高回答精确度哩🤪

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月24日(周六) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zidou-kiyn/ZanaoRobot] 证书问题还是X-Sc-...问题😭（具体见内容） (Issue #3)




 
好像集市升级后不需要那些加密参数了。直接有cookie就能获取了。
 代码如下
 `import requests
 
url = "https://c.zanao.com/sc-api/thread/info"
 headers = {
 "Host": "c.zanao.com",
 "Connection": "keep-alive",
 "X-Sc-Version": "2.7.0",
 "Accept": "application/json, text/plain, /",
 "X-Requested-With": "XMLHttpRequest",
 "X-Sc-Platform": "android",
 "X-Sc-Alias": "zzu",
 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 NetType/WIFI MicroMessenger/7.0.20.1781(0x6700143B) WindowsWechat(0x63090b19) XWEB/11177 Flue",
 "Origin": "https://c.zanao.com",
 "Sec-Fetch-Site": "same-origin",
 "Sec-Fetch-Mode": "cors",
 "Sec-Fetch-Dest": "empty",
 "Referer": "https://c.zanao.com/l/1Y21NOzl",
 "Accept-Encoding": "gzip, deflate, br",
 "Accept-Language": "zh-CN,zh;q=0.9",
 "Cookie": "user_token=user_token; SERVERID=SERVERID"
 }
 
Handling multipart form data
 
data = {
 "id": (None, "id"),
 "url": (None, "https://c.zanao.com/l/id"),
 "from": (None, ""),
 "isIOS": (None, "false")
 }
 
response = requests.post(url, headers=headers, files=data)
 
Print the response content
 
print(response.text)
 `
 其中cookie里面的user_token和serverid换成你自己抓出来的
 data中的id和url中的id也换成你们那边帖子的

**Comment by zidou-kiyn** [comment]
sign？加密参数吗。
我这个项目还只能算是demo，之后有空了考虑考虑重构。
现在对openai的api有了更多使用渠道。
有需要api的话可以联系我询问。

**Comment by Gotham-Jocker** [comment]
OK，好嘞，谢谢佬😘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月24日(周六) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zidou-kiyn/ZanaoRobot] 证书问题还是X-Sc-...问题😭（具体见内容） (Issue #3)




 
sign？加密参数吗。
 我这个项目还只能算是demo，之后有空了考虑考虑重构。
 现在对openai的api有了更多使用渠道。
 有需要api的话可以联系我询问。
